services:

  db:
    image: mysql
    restart: always
    ports:
      -  "1234:3306/tcp"
    environment:
      MYSQL_ROOT_PASSWORD: labubuntu
  server:
    build: .
    ports:
      -  "80:5432/tcp"

